# These are supported funding model platforms

github: [UFreedom]
patreon:  UFreedom
open_collective:  Replace with a single Open Collective username
ko_fi:  UFreedom
tidelift: UFreedom
custom: https://qr.alipay.com/paipai/personal.htm
